project: 
  type: manuscript

manuscript:
  article: index.ipynb
  #code-links:
  manuscript-url: https://sociest.github.io/ue-report/
  #meca-bundle
  #notebooks:
  #  - notebook: notebooks/notebook.ipynb
  #    title: Article Notebook
  #    download-url: notebooks/notebook.ipynb
  resources:
    - assets/data/database.csv
    - assets/data/municipios339.shp
  environment: 
    - assets/requeriments.txt

format:
  html:
    comments: false
  #    giscus: 
  #      repo: sociest/ue-report
  #      category: Q&A
  #      mapping: title
  #      reactions-enabled: true
  #      theme:
  #        light: light
  #        dark: dark_dimmed
  #      language: es
  docx: default
  #pdf:
  #  toc: true
  #  number-sections: true
  #  colorlinks: true
  #jasa-pdf:
  #  keep-tex: true    
execute:
  freeze: true
