project: 
  type: manuscript

execute:
  freeze: true

manuscript:
  article: index.ipynb
  manuscript-url: https://sociest.github.io/ue-report/
  code-links:
    - repo
    - binder
  resources:
    - assets/data/database.csv
    - assets/data/municipios339.shp
  environment: 
    - assets/requeriments.txt

format:
  html:
    theme: cosmo
    toc-location: left
    comments:
      giscus: 
         repo: sociest/ue-report
         category: Q&A
         mapping: title
         reactions-enabled: true
         theme:
           light: light
           dark: dark_dimmed
         language: es
    citations-hover: true
    crossrefs-hover: true
    title-block-style: manuscript  
    repo-url: https://github.com/sociest/ue-report
    repo-actions: [edit, issue]
  docx: default
  jasa-pdf:
    keep-tex: true
